"""add product reorder level

Revision ID: 6aa885992ffe
Revises: 2eb4ce06875b
Create Date: 2026-09-05 09:16:35.809626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aa885992ffe'
down_revision: Union[str, Sequence[str], None] = '2eb4ce06875b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('reorder_level', sa.Numeric(precision=12, scale=3), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'reorder_level')
    # ### end Alembic commands ###
