"""create stock transactions table

Revision ID: a371e1fd5ab8
Revises: 3b0f50d6f09f
Create Date: 2026-09-04 18:05:21.640032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a371e1fd5ab8'
down_revision: Union[str, Sequence[str], None] = '3b0f50d6f09f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=30), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('transaction_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_transactions_id'), 'stock_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_stock_transactions_product_id'), 'stock_transactions', ['product_id'], unique=False)
    op.create_index(op.f('ix_stock_transactions_transaction_date'), 'stock_transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_stock_transactions_transaction_type'), 'stock_transactions', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_stock_transactions_warehouse_id'), 'stock_transactions', ['warehouse_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_transactions_warehouse_id'), table_name='stock_transactions')
    op.drop_index(op.f('ix_stock_transactions_transaction_type'), table_name='stock_transactions')
    op.drop_index(op.f('ix_stock_transactions_transaction_date'), table_name='stock_transactions')
    op.drop_index(op.f('ix_stock_transactions_product_id'), table_name='stock_transactions')
    op.drop_index(op.f('ix_stock_transactions_id'), table_name='stock_transactions')
    op.drop_table('stock_transactions')
    # ### end Alembic commands ###
